services:
    konekt_courier.fancourier.configuration:
        class: Konekt\Courier\FanCourier\Model\Configuration
        arguments:
            - %konekt_courier.fancourier.configuration.username%
            - %konekt_courier.fancourier.configuration.user_pass%
            - %konekt_courier.fancourier.configuration.client_id%

    konekt_courier.fancourier.command.factory:
        class: Konekt\Courier\FanCourier\Transaction\CommandFactory
        arguments:
            - "@konekt_courier.fancourier.configuration"

    konekt_courier.fancourier.request.processor:
        class: Konekt\Courier\Common\RequestProcessor
        arguments:
            - "@konekt_courier.fancourier.command.factory"

    konekt_courier.fancourier.package.factory:
        class: Konekt\Courier\FanCourier\Bridge\Sylius\PackageFactory
        arguments:
            - "@sylius.province_naming_provider"